import { clock } from "../shared/composition.mjs";
export function videoDescription(track, options) {
  const artwork = track.hasArtwork
    ? `Cover art: ${track.artworkSourceUrl || track.sourceUrl || "original Finds Studio artwork (included as cover-art.jpg)"}`
    : "Cover art: generated by Finds Studio.";
  return [
    `SoundCloud Finds · Vol. ${options.episode.padStart(3, "0")}`,
    "",
    `On repeat: “${track.title}” by ${track.artist}.`,
    "A little less scrolling. A little more listening.",
    "",
    `Artist: ${track.artist}`,
    track.album ? `Album: ${track.album}` : null,
    `Track: ${track.title}`,
    `Featured moment: ${clock(options.start)}–${clock(options.start + options.duration)}`,
    track.sourceUrl
      ? `Listen & support the artist: ${track.sourceUrl}`
      : "Audio: original Finds Studio demo.",
    artwork,
    track.artworkCredit ? `Artwork credit: ${track.artworkCredit}` : null,
    "",
    "Thanks for watching. Save this find for later.",
    "#SoundCloudFinds #MusicDiscovery #NowPlaying #NewMusic",
  ]
    .filter((line) => line !== null)
    .join("\n");
}
